# Generated by Django 4.1.1 on 2022-11-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsgsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('new_msg', models.CharField(default=1, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Msgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgs_name', models.CharField(max_length=1000, null=True)),
                ('new_msgs', models.CharField(default=1, max_length=2, null=True)),
                ('msgs_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Msgs_Api.msgstypes')),
            ],
        ),
    ]
